apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mywebapp
  name: mywebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywebapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mywebapp
    spec:
      containers:
      - image: ykhadilkar/mywebapp
        name: mywebapp
status: {}