apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: aspnetapp
  name: aspnetapp
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: aspnetapp
  type: ClusterIP
status:
  loadBalancer: {}