apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mywebapp
  name: mywebapp
spec:
  ports:
  - name: mywebapp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mywebapp
  type: ClusterIP
status:
  loadBalancer: {}